name: Send status to Webhook

on:
  workflow_dispatch:
  push:
    branches: [ main, dev ]

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send status to Discord
        uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: ${{ secrets.discord_webhook_url }} # required
          status: ${{ job.status }}
        if: always() # or failure() or success()
